export const IMAGES: Record<string, string> = {
  'detail-evaluation-chart': '../../../src/assets/images/detail-evaluation-chart.png',
  'grade-small': '../../../src/assets/images/grade-small.png',
  grade: '../../../src/assets/images/grade.png',
  grammar: '../../../src/assets/images/grammar.png',
  'improvement-01': '../../../src/assets/images/improvement-01.png',
  'improvement-02': '../../../src/assets/images/improvement-02.png',
  'improvement-03': '../../../src/assets/images/improvement-03.png',
  'improvement-04': '../../../src/assets/images/improvement-04.png',
  'improvement-05': '../../../src/assets/images/improvement-05.png',
  'loading-project-evaluation': '../../../src/assets/images/loading-project-evaluation.png',
  'loading-total-evaluation-small': '../../../src/assets/images/loading-total-evaluation-small.png',
  'loading-total-evaluation': '../../../src/assets/images/loading-total-evaluation.png',
  logic: '../../../src/assets/images/logic.png',
  'project-01': '../../../src/assets/images/project-01.png',
  'project-02': '../../../src/assets/images/project-02.png',
  'project-03': '../../../src/assets/images/project-03.png',
  'project-04': '../../../src/assets/images/project-04.png',
  readability: '../../../src/assets/images/readability.png',
  redundancy: '../../../src/assets/images/redundancy.png',
  'step-card-01': '../../../src/assets/images/step-card-01.png',
  'step-card-02': '../../../src/assets/images/step-card-02.png',
  'total-evaluation': '../../../src/assets/images/total-evaluation.png',
  translation: '../../../src/assets/images/translation.png',
};
